### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by evayfang2019** [yyren/FVC#3]
Hi,  I tried to install it through Docker but failed. When entered the URL(https://bmap.sjtu.edu.cn/softstorage/details/31) you gave, I clicked the download button and found it was an empty file. Can you give more details about installing FVC from Docker?
Thanks!

**Comment by yyren** [comment]
Please try downloading again, we have updated the service today.

**Comment by evayfang2019** [comment]
Thanks! 
I encountered an error.
[xyz@bogon biosoft]$ singularity exec --bind /data/xyz:/mnt/data FVC_image.sif /mnt/data/biosoft/FVC-1.0.0/Features_construction.sh -i /mnt/data/project_230823/07.01.deepvariant/B01.minimap2.output.vcf.gz     -b /mnt/data/project_230823/03.aligned/B01.minimap2.aligned.sort.bam    -r /mnt/data/project_230823/hg38.fa     -t 40     -p /mnt/data/project_230823/FVC/out_snv.record     -q /mnt/data/project_230823/FVC/out_indel.record
Start features construction: 20230909_01_16_46
Step 1/4 Creat temp folder: /mnt/data/project_230823/FVC/temp_20230909011646
Step 2/4 Start VariantAnnotator: 20230909_01_16_50
grep: /mnt/data/project_230823/FVC/temp_20230909011646/0_raw_add_feature.vcf: No such file or directory
Error - VariantAnnotator Failed

Is this container not suitable for filtering VCF files generated by deepvariant？


> Please try downloading again, we have updated the service today.

**Comment by yyren** [comment]
Hi evayfang,

Please uncompress the 'B01.minimap2.output.vcf.gz' file and use the uncompressed format VCF file as the input file, i.e, '-i B01.minimap2.output.vcf'. 

If this error still persist, would it be possible for you to upload both a subset of the VCF file (including the VCF header information) and the BAM file containing the reads of the locations of the subset variants (including the BAM header information) so that we can reproduce this error?

**Comment by evayfang2019** [comment]
Hi yyren, 
The same problem occurs even with uncompressed files. Could you please check the subset file and reproduce this error?
Thanks!

[subset_file.zip](https://github.com/yyren/FVC/files/12568552/subset_file.zip)

**Comment by yyren** [comment]
Thank you. Could you please provide the download URL of the human reference file you used in the read alignment step.

**Comment by evayfang2019** [comment]
> Thank you. Could you please provide the download URL of the human reference file you used in the read alignment step.

https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/latest/hg38.fa.gz

**Comment by yyren** [comment]
Hi evayfang,

The FVC tool necessitates the consistent labeling of the sampleID in both the BAM (specified under the @RG SM tag, e.g., B01) and the VCF file (located in the 10th column name). In instances where there is a discrepancy between the two, FVC will automatically amend the sampleID in the VCF file to match that of the BAM file.

Unfortunately, it appears that your BAM file lacks a designated sampleID, specifically missing an SM tag, which has triggered the error message you received.

To address this, we have refined our '_**Features_construction.sh**_' script to be more adaptive to such scenarios. Now, if the BAM file is missing the sampleID, the script will retrieve and apply the sampleID from the VCF file to ensure uniformity and prevent this error from occurring in the future. 

The output file has been listed in the attachment. Please try running your process again with the updated script.


[B01.zip](https://github.com/yyren/FVC/files/12602977/B01.zip)

**Comment by evayfang2019** [comment]
Dear Dr. Ren,

Thanks for your kind help. Now, I can smoothly run step 1 (Features construction) and get  `out_indel.record` and `out_snv.record`. Unfortunately, when I ran step 2 (Filtering), another error was reported. Could you please help me again?

> B01.minimap2.output.vcf: generated by DeepVariant version1.5
> out_snv.record & out_indel.record: generated by step 1 (Features construction)
> deepvariant_snv_xgbdef.model & deepvariant_indel_xgbdef.model: From the latest FVC tool.

**THE CODE:**
```shell
singularity exec --bind /data/xyz:/mnt/data /data/xyz/biosoft/FVC_image.sif \ 
     bash/mnt/data/biosoft/FVC/Supervised_learning_filtering.sh \
     -f filter \
     -i /mnt/data/project_230823/B01.minimap2.output.vcf \
     -o /mnt/data/project_230823/B01.minimap2.snpindel_filtered.vcf \
     -p /mnt/data/project_230823/FVC/out_snv.record \
     -q /mnt/data/project_230823/FVC/out_indel.record \
     -m /mnt/data/biosoft/FVC/Pre-trained_Models/deepvariant_snv_xgbdef.model \
     -n /mnt/data/biosoft/FVC/Pre-trained_Models/deepvariant_indel_xgbdef.model
``` 

**ERROR REPORTS:**
```
loading /mnt/data/biosoft/FVC/Pre-trained_Models/deepvariant_snv_xgbdef.model
Traceback (most recent call last):
  File "/mnt/data/biosoft/FVC/FVC_Prediction.py", line 44, in <module>
    y_pred, y_score = predictor_series(X_test, clfkit[0], normalizer)
  File "/mnt/data/biosoft/FVC/FVC_Prediction.py", line 11, in predictor_series
    X_test = normalizer.transform(X_test)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_data.py", line 883, in transform
    X = self._validate_data(X, reset=False,
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 437, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 365, in _check_n_features
    raise ValueError(
ValueError: X has 18 features, but StandardScaler is expecting 20 features as input.
loading /mnt/data/biosoft/FVC/Pre-trained_Models/deepvariant_indel_xgbdef.model
Traceback (most recent call last):
  File "/mnt/data/biosoft/FVC/FVC_Prediction.py", line 44, in <module>
    y_pred, y_score = predictor_series(X_test, clfkit[0], normalizer)
  File "/mnt/data/biosoft/FVC/FVC_Prediction.py", line 11, in predictor_series
    X_test = normalizer.transform(X_test)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_data.py", line 883, in transform
    X = self._validate_data(X, reset=False,
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 437, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 365, in _check_n_features
    raise ValueError(
ValueError: X has 18 features, but StandardScaler is expecting 20 features as input.
can not open /mnt/data/project_230823/FVC_predict_snv.txt
rm: cannot remove '/mnt/data/project_230823/FVC_predict_snv.txt': No such file or directory
rm: cannot remove '/mnt/data/project_230823/FVC_predict_indel.txt': No such file or directory
```

Best Regards,
evayfang

**Comment by yyren** [comment]
Hi evayfang,

We conducted tests and identified the source of the error. It appears that when using minimap2 for aligning the BAM file, FVC is unable to generate essential features such as 'MQ: RMS Mapping Quality' and 'MQRankSum: Z-score From Wilcoxon rank sum test of Alt vs. Ref read mapping qualities'.

To avoid this issue in the future, we recommend utilizing bwa-mem for read alignments when incorporating FVC into your variant calling pipeline. This should facilitate a smoother process and more reliable results. Thank you for your understanding and we will provide a version to support the filtering of variant calls generated from the minimap2.

**Comment by evayfang2019** [comment]
Hi Dr. Ren, thanks again. Very nice work! Hope to see more excellent research in the future.
